from . import res_user
from . import setting
from . import product_template
from . import product_category
from . import product_image
from . import product_brand_ept
from . import order_line
from . import res_partner
from . import sales_target